---
- name: Install networking packages
  ansible.builtin.apt:
    name: "{{ pkgs }}"
    state: present
  vars:
    pkgs:
      - netplan.io
      - systemd-resolved
      - libnss-resolve

- name: Make sure networking services are enabled
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  with_items:
    - systemd-networkd
    - systemd-resolved

- name: Create resolved.conf.d
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: "0755"

- name: Disable llmnr
  ansible.builtin.copy:
    src: 10-disable-llmnr.conf
    dest: /etc/systemd/resolved.conf.d/10-disable-llmnr.conf
    mode: "0644"

- name: Disable stub
  ansible.builtin.copy:
    src: 10-disable-stub.conf
    dest: /etc/systemd/resolved.conf.d/10-disable-stub.conf
    mode: "0644"

- name: Disable mdns
  ansible.builtin.copy:
    src: 10-disable-mdns.conf
    dest: /etc/systemd/resolved.conf.d/10-disable-mdns.conf
    mode: "0644"

- name: Cleanup files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apt/apt.conf.d/00CDMountPoint
    - /etc/apt/apt.conf.d/00trustcdrom
    - /etc/apt/sources.list~

- name: Copy sources.list
  ansible.builtin.copy:
    src: sources.list
    dest: /etc/apt/sources.list
    mode: "0644"

- name: Disable apt timers
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - apt-daily.timer
    - apt-daily-upgrade.timer

- name: Setup apt mirrors
  when: not immutable
  block:
    - name: Create mirror dir
      ansible.builtin.file:
        path: /etc/apt/mirrors
        state: directory
        mode: "0755"

    - name: Copy mirrorfiles
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/apt/mirrors/
        mode: "0644"
      with_items:
        - debian.list
        - debian-security.list

    - name: Copy debian sources
      ansible.builtin.copy:
        src: debian.sources
        dest: /etc/apt/sources.list.d/debian.sources
        mode: "0644"

- name: Truncate machine-id
  ansible.builtin.command: truncate -s0 /etc/machine-id
  changed_when: true

- name: Link dbus machine id to /etc/machine-id
  ansible.builtin.file:
    src: /etc/machine-id
    dest: /var/lib/dbus/machine-id
    state: link
    force: true

- name: Stop systemd random seed service
  ansible.builtin.systemd:
    name: systemd-random-seed.service
    state: stopped

- name: Remove random seed
  ansible.builtin.file:
    path: /var/lib/systemd/random-seed
    state: absent

- name: Remove installer logs
  ansible.builtin.file:
    path: /var/log/installer
    state: absent

- name: Purge obsolete networking packages
  ansible.builtin.apt:
    name: "{{ pkgs }}"
    state: absent
    purge: true
  vars:
    pkgs:
      - ifupdown

- name: Replace interfaces file
  ansible.builtin.file:
    path: /etc/network
    state: absent

- name: Stop systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped

- name: Link resolv.conf to file managed by systemd-resolved
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true

- name: Reset hosts file
  ansible.builtin.copy:
    src: hosts
    dest: /etc/hosts
    mode: "0644"

- name: Remove hostname
  ansible.builtin.file:
    path: /etc/hostname
    state: absent

- name: Clean apt cache
  ansible.builtin.apt:
    clean: true

- name: Find all apt lists
  ansible.builtin.find:
    file_type: any
    paths: /var/lib/apt/lists
    recurse: true
  register: apt

- name: Remove all apt lists files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ apt.files }}"

- name: Remove cdrom lists
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/apt/cdroms.list
    - /var/lib/apt/cdroms.list~

- name: Remove ssh host keys
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/ssh/ssh_host_dsa_key
    - /etc/ssh/ssh_host_dsa_key.pub
    - /etc/ssh/ssh_host_ecdsa_key
    - /etc/ssh/ssh_host_ecdsa_key.pub
    - /etc/ssh/ssh_host_ed25519_key
    - /etc/ssh/ssh_host_ed25519_key.pub
    - /etc/ssh/ssh_host_rsa_key
    - /etc/ssh/ssh_host_rsa_key.pub

- name: Remove builder ssh key from root user
  ansible.builtin.file:
    path: /root/.ssh
    state: absent

- name: Find all temp files
  ansible.builtin.find:
    file_type: any
    paths:
      - /tmp
      - /var/tmp
    recurse: true
  register: tmp

- name: Remove all tmp files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ tmp.files }}"

- name: Stop systemd journal before clearing all logs
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
  with_items:
    - systemd-journald-dev-log.socket
    - systemd-journald-audit.socket
    - systemd-journald.service
    - systemd-journald.socket

- name: Find all systemd journal dirs
  ansible.builtin.find:
    file_type: any
    paths: /var/log/journal
    recurse: false
  register: journal

- name: Remove systemd journal
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ journal.files }}"

- name: Find all log files
  ansible.builtin.find:
    file_type: file
    paths: /var/log
    recurse: true
  register: logs

- name: Truncate all log files
  ansible.builtin.command: truncate -s0 {{ item.path }}
  changed_when: true
  loop: "{{ logs.files }}"

- name: Run fstrim
  ansible.builtin.command: fstrim -a
  changed_when: true
