---
- name: Install network storage client libraries and tools
  ansible.builtin.apt:
    name: "{{ pkgs }}"
    state: present
  vars:
    pkgs:
      - nfs-common
      - open-iscsi

- name: Disable nfsv3
  ansible.builtin.copy:
    src: 10-disable-nfsv3.conf
    dest: /etc/nfs.conf.d/10-disable-nfsv3.conf
    mode: "0644"

- name: Mask rpcbind services
  ansible.builtin.systemd:
    name: "{{ item }}"
    masked: true
    state: stopped
  with_items:
    - rpc-statd.service
    - rpcbind.service
    - rpcbind.socket

- name: Generate unique initiatorname on daemon start
  ansible.builtin.copy:
    src: initiatorname.iscsi
    dest: /etc/iscsi/initiatorname.iscsi
    mode: "0600"
