---
- name: Cleanup unnecessary packages
  ansible.builtin.apt:
    name: "{{ cleanup_packages }}"
    state: absent
    purge: true
    autoremove: true

- name: Remove cdrom from fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^/dev/sr0'
    state: absent

- name: Remove cdrom dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /media/cdrom
    - /media/cdrom0

- name: Blacklist some modules
  ansible.builtin.copy:
    src: blacklist.conf
    dest: /etc/modprobe.d/blacklist.conf
    mode: "0644"

- name: Run daemon reload after modifying fstab
  ansible.builtin.systemd:
    daemon_reload: true

- name: Install common utilities
  ansible.builtin.apt:
    name: "{{ common_utilities }}"
    state: present

- name: Install chrony
  ansible.builtin.apt:
    name: chrony
    state: present

- name: Setup ptp_kvm module
  when: ptp_kvm
  block:
    - name: Load ptp_kvm module on boot
      ansible.builtin.copy:
        src: ptp_kvm.conf
        dest: /etc/modules-load.d/ptp_kvm.conf
        mode: "0644"

    - name: Override chrony.conf
      ansible.builtin.copy:
        src: chrony.conf
        dest: /etc/chrony/chrony.conf
        mode: "0644"

- name: Install cloud-init
  ansible.builtin.apt:
    name: "{{ pkgs }}"
    state: present
  vars:
    pkgs:
      - cloud-init
      - cloud-initramfs-growroot
      - sudo

- name: Debian cloud image configuration
  ansible.builtin.template:
    src: 01_debian_cloud.cfg.j2
    dest: /etc/cloud/cloud.cfg.d/01_debian_cloud.cfg
    mode: "0644"

- name: Debian disable dsa key generation
  ansible.builtin.copy:
    src: 02_disable_dsa_ssh.cfg
    dest: /etc/cloud/cloud.cfg.d/02_disable_dsa_ssh.cfg
    mode: "0644"

- name: Setup cloud kernel
  when: cloud_kernel
  block:
    - name: Remove linux images
      ansible.builtin.apt:
        name: linux-image-*
        state: absent
        purge: true
        force: true
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Install linux cloud kernel
      ansible.builtin.apt:
        name: linux-image-cloud-{{ architecture[ansible_architecture] }}
        state: present

- name: Setup grub cloud
  when: ansible_architecture == "x86_64"
  block:
    - name: Remove grub-efi-amd64
      ansible.builtin.apt:
        name: grub-efi-amd64
        state: absent
        purge: true

    - name: Install grub-cloud-amd64
      ansible.builtin.apt:
        name: grub-cloud-amd64
        state: present

    - name: Run efi grub install
      ansible.builtin.command: >
        grub-install --removable --target=x86_64-efi --efi-directory=/boot/efi
        --bootloader-id=debian
      changed_when: true

    - name: Run bios grub install
      ansible.builtin.command: grub-install --target=i386-pc /dev/sda
      changed_when: true

- name: Set grub timeout to 0
  ansible.builtin.copy:
    src: 15_timeout.cfg
    dest: /etc/default/grub.d/15_timeout.cfg
    mode: "0755"

- name: Update grub config
  ansible.builtin.command: update-grub
  changed_when: true

- name: Harden ssh
  ansible.builtin.copy:
    src: 10-hardening.conf
    dest: /etc/ssh/sshd_config.d/10-hardening.conf
    mode: "0644"

- name: Setup network storage tools
  when: network_storage_tools
  block:
    - name: Install network storage client libraries and tools
      ansible.builtin.apt:
        name: "{{ pkgs }}"
        state: present
      vars:
        pkgs:
          - nfs-common
          - open-iscsi

    - name: Disable nfsv3
      ansible.builtin.copy:
        src: 10-disable-nfsv3.conf
        dest: /etc/nfs.conf.d/10-disable-nfsv3.conf
        mode: "0644"

    - name: Mask rpcbind services
      ansible.builtin.systemd:
        name: "{{ item }}"
        masked: true
        state: stopped
      with_items:
        - rpc-statd.service
        - rpcbind.service
        - rpcbind.socket

    - name: Generate unique initiatorname on daemon start
      ansible.builtin.copy:
        src: initiatorname.iscsi
        dest: /etc/iscsi/initiatorname.iscsi
        mode: "0600"

- name: Set ndisc notify
  ansible.builtin.copy:
    src: 90-ndisc-notify.conf
    dest: /etc/sysctl.d/90-ndisc-notify.conf
    mode: "0644"
