name: Setup Packer
description: Setup Packer and dependencies

inputs:
  version:
    description: Packer version
    required: false
    default: 1.10.*

runs:
  using: composite
  steps:
    - name: Setup Hashicorp repository
      run: |
        curl https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    - name: Install Packer and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y packer=${{ inputs.version }} qemu-kvm ovmf ansible-core
    - name: Enable kvm group permissions
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
