---
- name: Import base configuration playbook
  ansible.builtin.import_playbook: base.yml

- name: Nameserver playbook
  hosts: nameserver
  roles:
    - nameserver

- name: Import sysprep playbook
  ansible.builtin.import_playbook: sysprep.yml
