---
- name: Import base configuration playbook
  ansible.builtin.import_playbook: base.yml

- name: Router playbook
  hosts: router
  roles:
    - router

- name: Import sysprep playbook
  ansible.builtin.import_playbook: sysprep.yml
