---
- name: Install cloud-init
  ansible.builtin.apt:
    name: "{{ pkgs }}"
    state: present
  vars:
    pkgs:
      - cloud-init
      - cloud-initramfs-growroot
      - sudo

- name: Debian cloud image configuration
  ansible.builtin.template:
    src: 01_debian_cloud.cfg.j2
    dest: /etc/cloud/cloud.cfg.d/01_debian_cloud.cfg
    mode: "0644"

- name: Debian disable dsa key generation
  ansible.builtin.copy:
    src: 02_disable_dsa_ssh.cfg
    dest: /etc/cloud/cloud.cfg.d/02_disable_dsa_ssh.cfg
    mode: "0644"
