---
- name: Install open-iscsi
  ansible.builtin.apt:
    name: open-iscsi
    state: present

- name: Generate unique initiatorname on daemon start
  ansible.builtin.copy:
    src: initiatorname.iscsi
    dest: /etc/iscsi/initiatorname.iscsi
    mode: "0600"
