name: Shellcheck
description: Setup and run shellcheck

inputs:
  version:
    description: Shellcheck version
    required: false
    default: stable
  scripts:
    description: Space separated list of shell scripts
    required: true

runs:
  using: composite
  steps:
    - name: Setup shellcheck
      run: |
        mkdir -p ~/.local/bin
        curl -sL "https://github.com/koalaman/shellcheck/releases/download/${{ inputs.version }}/shellcheck-${{ inputs.version }}.linux.x86_64.tar.xz" | tar -xJ --strip-components=1 -C ~/.local/bin --exclude=*.txt
        shellcheck --version
      shell: bash
    - name: Run shellcheck
      run: ~/.local/bin/shellcheck ${{ inputs.scripts }}
      shell: bash
