name: Continuous integration

on:
  pull_request:
    branches:
      - main

jobs:
  check-changes:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      ansible: ${{ steps.changes.outputs.ansible }}
      shell: ${{ steps.changes.outputs.shell }}
      shell_files: ${{ join(fromJSON(steps.changes.outputs.shell_files), ' ') }}
      packer: ${{ steps.changes.outputs.packer }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          list-files: json
          filters: |
            ansible:
              - 'ansible/**'
            shell:
              - '*.sh'
              - '**/*.sh'
            packer:
              - '*.hcl'

  ansible-lint:
    name: Lint Ansible
    needs: check-changes
    runs-on: ubuntu-latest
    if: ${{ needs.check-changes.outputs.ansible == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ./.github/actions/ansible-lint
        with:
          target: ansible

  shellcheck:
    name: Lint shellscripts
    needs: check-changes
    runs-on: ubuntu-latest
    if: ${{ needs.check-changes.outputs.shell == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run shellcheck
        uses: ./.github/actions/shellcheck
        with:
          scripts: ${{ needs.check-changes.outputs.shell_files }}

  packer-check-changes:
    name: Check Packer template changes
    needs: check-changes
    runs-on: ubuntu-latest
    if: ${{ needs.check-changes.outputs.ansible == 'true' || needs.check-changes.outputs.packer == 'true' }}
    outputs:
      variants: ${{ steps.changes.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            generic:
              - '*.pkr.hcl'
              - 'ansible/roles/baseimage/**'
              - 'ansible/roles/sysprep/**'
              - 'ansible/host_vars/generic.yml'
              - 'ansible/generic.yml'
            router:
              - '*.pkr.hcl'
              - 'ansible/roles/baseimage/**'
              - 'ansible/roles/sysprep/**'
              - 'ansible/host_vars/router.yml'
              - 'ansible/router.yml'
            nameserver:
              - '*.pkr.hcl'
              - 'ansible/roles/baseimage/**'
              - 'ansible/roles/sysprep/**'
              - 'ansible/host_vars/nameserver.yml'
              - 'ansible/nameserver.yml'

  packer-validate:
    name: Validate Packer template
    needs: packer-check-changes
    runs-on: ubuntu-latest
    if: ${{ needs.packer-check-changes.outputs.variants != '[]' }}
    strategy:
      matrix:
        variant: ${{ fromJSON(needs.packer-check-changes.outputs.variants) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup packer
        uses: ./.github/actions/setup-packer
      - name: Initialize Packer
        run: make init
      - name: Validate Packer template
        run: make validate VARIANT=${{ matrix.variant }}

  packer-build:
    name: Build Packer template
    needs: ["ansible-lint", "shellcheck", "packer-check-changes","packer-validate"]
    if: |
      (needs.ansible-lint.result == 'success' || needs.ansible-lint.result == 'skipped') &&
      (needs.shellcheck.result == 'success' || needs.ansible-lint.result == 'skipped') &&
      needs.packer-validate.result == 'success'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ${{ fromJSON(needs.packer-check-changes.outputs.variants) }}
    env:
      PKR_VAR_cpus: 2
      PKR_VAR_memory: 4096
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup packer
        uses: ./.github/actions/setup-packer
      - name: Initialize Packer
        run: make init
      - name: Build Packer template
        run: make build VARIANT=${{ matrix.variant }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.variant }}-${{ github.sha }}
          retention-days: 1
          path: |
            images/*
            !images/efivars.fd

  trivy-scan:
    name: Scan Packer build artifacts
    needs: ["packer-check-changes", "packer-build"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ${{ fromJSON(needs.packer-check-changes.outputs.variants) }}
    steps:
      - name: Setup qemu-utils
        run: sudo apt-get update && sudo apt-get install -y qemu-utils
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.variant }}-${{ github.sha }}
          path: artifacts
      - name: Convert qcow2 image to raw format
        run: |
          mkdir raw-artifacts
          artifact=$(ls artifacts/*.qcow2)
          qemu-img convert -f qcow2 -O raw $artifact raw-artifacts/$(basename $artifact | sed 's/\.qcow2$/.raw/')
      - name: Mount raw image
        run: |
          artifact=$(ls raw-artifacts/*.raw)
          sudo losetup -P /dev/loop0 $artifact
          mkdir rootfs
          sudo mount /dev/loop0p4 rootfs
          sudo mount /dev/loop0p3 rootfs/boot
          sudo mount /dev/loop0p2 rootfs/boot/efi
      - name: Run trivy scan on rootfs
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: rootfs
          scan-ref: rootfs
          ignore-unfixed: true
          format: sarif
          output: ${{ matrix.variant }}.sarif
      - name: Upload scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ matrix.variant }}.sarif
          category: ${{ matrix.variant }}

  check-results:
    name: Check results
    needs: ["trivy-scan"]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Result succesful
        if: ${{ needs.trivy-scan.result == 'success' || needs.trivy-scan.result == 'skipped' }}
        run: exit 0
      - name: Result failure
        if: ${{ needs.trivy-scan.result == 'cancelled' || needs.trivy-scan.result == 'failure' }}
        run: exit 1
