name: Continuous integration

on:
  pull_request:
    branches:
      - main

jobs:
  check-changes:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      ansible: ${{ steps.changes.outputs.ansible }}
      shell: ${{ steps.changes.outputs.shell }}
      shell_files: ${{ join(fromJSON(steps.changes.outputs.shell_files), ' ') }}
      packer: ${{ steps.changes.outputs.packer }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          list-files: json
          filters: |
            ansible:
              - 'ansible/**'
            shell:
              - '*.sh'
              - '**/*.sh'
            packer:
              - '*.hcl'

  ansible-lint:
    name: Lint Ansible
    needs: check-changes
    runs-on: ubuntu-latest
    if: ${{ needs.check-changes.outputs.ansible == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ./.github/actions/ansible-lint
        with:
          target: ansible

  shellcheck:
    name: Lint shellscripts
    needs: check-changes
    runs-on: ubuntu-latest
    if: ${{ needs.check-changes.outputs.shell == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run shellcheck
        uses: ./.github/actions/shellcheck
        with:
          scripts: ${{ needs.check-changes.outputs.shell_files }}

  packer-check-changes:
    name: Check Packer template changes
    needs: check-changes
    runs-on: ubuntu-latest
    if: ${{ needs.check-changes.outputs.ansible == 'true' || needs.check-changes.outputs.packer == 'true' }}
    outputs:
      variants: ${{ steps.changes.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            generic:
              - '*.pkr.hcl'
              - 'ansible/roles/baseimage/**'
              - 'ansible/roles/sysprep/**'
              - 'ansible/host_vars/generic.yml'
              - 'ansible/generic.yml'
            router:
              - '*.pkr.hcl'
              - 'ansible/roles/baseimage/**'
              - 'ansible/roles/sysprep/**'
              - 'ansible/host_vars/router.yml'
              - 'ansible/router.yml'
            nameserver:
              - '*.pkr.hcl'
              - 'ansible/roles/baseimage/**'
              - 'ansible/roles/sysprep/**'
              - 'ansible/host_vars/nameserver.yml'
              - 'ansible/nameserver.yml'

  packer-validate:
    name: Validate Packer template
    needs: packer-check-changes
    runs-on: ubuntu-latest
    if: ${{ needs.packer-check-changes.outputs.variants != '[]' }}
    strategy:
      matrix:
        variant: ${{ fromJSON(needs.packer-check-changes.outputs.variants) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup packer
        uses: ./.github/actions/setup-packer
      - name: Initialize Packer
        run: make init
      - name: Validate Packer template
        run: make validate VARIANT=${{ matrix.variant }}

  packer-build:
    name: Build Packer template
    needs: ["ansible-lint", "shellcheck", "packer-check-changes","packer-validate"]
    if: |
      (needs.ansible-lint.result == 'success' || needs.ansible-lint.result == 'skipped') &&
      (needs.shellcheck.result == 'success' || needs.ansible-lint.result == 'skipped') &&
      needs.packer-validate.result == 'success'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ${{ fromJSON(needs.packer-check-changes.outputs.variants) }}
    env:
      PKR_VAR_cpus: 2
      PKR_VAR_memory: 4096
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup packer
        uses: ./.github/actions/setup-packer
      - name: Initialize Packer
        run: make init
      - name: Build Packer template
        run: make build VARIANT=${{ matrix.variant }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.variant }}-${{ github.sha }}
          retention-days: 1
          path: |
            images/*
            !images/efivars.fd

  check-results:
    name: Check results
    needs: ["packer-build"]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Result succesful
        if: ${{ needs.packer-build.result == 'success' || needs.packer-build.result == 'skipped' }}
        run: exit 0
      - name: Result failure
        if: ${{ needs.packer-build.result == 'cancelled' || needs.packer-build.result == 'failure' }}
        run: exit 1
